### ISSUE TITLE
request: `Serializable` mixin for attrs conversion

### ISSUE THREAD

**Issue by Dworv** [retuxteam/retux#41]
### What's the feature?

At the moment, attrs is not able to serialize Discord structures inside of other Discord structures because it uses `converter`s, which take one positional argument. Meanwhile, the classes we use in those converters take multiple key-word arguments, making them incompatible. The `Serializable` mixin aims to solve this by providing a `convert` class method which takes a single `dict` positional argument and returning an instance of the object.

### How does it work?

```py
class Serializable:
  @classmethod
  async def convert(cls, data: dict):
```
```py
channels: list[Channel] = field(converter=list_c(Channel.convert))
```

### Code of Conduct

- [X] I agree.

**Comment by i0bs** [comment]
Flagged as high priority

**Comment by i0bs** [comment]
As discussed within the support server, the best course of action is to keep it to the proposed spec given here but instead shorthand it as `_c`. This would represent a private-access class method for the converted result. It will be as minimal in possible for line changes across all of our dataclasses and keeps serialisation separate to the real contents of the resource. The Gateway dispatcher will have a sanitisation method to properly check for any private-access methods and attributes as well to avoid sending it.
