### ISSUE TITLE
request: remove `_Event` and make a `_bot_inst` attribute for `Object`

### ISSUE THREAD

**Issue by Dworv** [retuxteam/retux#54]
### What's the feature?

This will solve a problem that we have been running into with events: providing classes generated by events an instance of `Bot` so that helper methods can easily be created. However, using the `_Event` class as a parent class to provide a field for this causes multiple issues, including attrs breaking positional arguments after inheritance and circular import hell. Luckily, there is a solution that no only solves the problem without any major downsides, but also uses an existing class and removing the need for a new parent class on many resources: adding the field to `User`. It has been discussed, and this attribute will probably best be named `_bot_inst` to avoid conflicting with any Discord provided fields. This is one of the few changes I have found that we need to make in able to return to a state in the library where we can launch a bot without encountering any errors.

### How does it work?

```py
@define(kw_only=True)
class Object:
    """
    Represents the base object form of a resource from Discord.

    Attributes
    ----------
    id : `Snowflake`
        The ID associated to the object.
    """ # DOCUMENTATION NEEDED

    id: str | Snowflake = field(converter=Snowflake)
    """The ID associated to the object."""
    _bot_inst: Union["Bot", None] = field(default=None)
    # DOCUMENT ME
```

### Code of Conduct

- [X] I agree.

**Comment by i0bs** [comment]
Linked to #55 .

**Comment by i0bs** [comment]
Noting the documentation, we only need to document the attribute and not the docstring
