### ISSUE TITLE
request: simplify sanitization by moving it to `Serialize._c`

### ISSUE THREAD

**Issue by Dworv** [retuxteam/retux#55]
### What's the feature?

Ok, hear me out. At the moment, the sanitization for objects from Discord is really complicated (and doesn't actually work). Refactoring it to `Serializable._c` simplifies the gateway dispatching and allows for sanitizing recursively instead of only sanitizing the immediate fields of the object sent by Discord.

### How does it work?

Old gateway code:
```py
sanitised_data = dataclass_v(data)

# TODO: create a better dataclass validator for sanitising values.
# This is simply deleting anything the Gateway gives us for the event
# that the associated dataclass doesn't have as a listed attrib.
for kwarg in kwargs:
    if kwarg not in sanitised_data:
        logger.debug(
            f"Field {kwarg} found missing from {type(data)}, removing from dispatch."
        )
        del kwargs[kwarg]

await bot._trigger(
    _name.lower(),
    data(
        _name.lower(),
        bot if "id" in kwargs else MISSING,
        *args,
        **{k: v for k, v in kwargs.items() if not k.startswith("_")},
    ),
)
```
New gateway code:
```py
kwargs["bot_inst"] = bot
bot._trigger(_name.lower(), data._c(kwargs))
```

### Code of Conduct

- [X] I agree.

**Comment by i0bs** [comment]
Why are we dropping the sanitisation? This is extremely important to protect the library from throwing runtime exceptions like `TypeError` or `AttributeError` for missing attributes (aka. undocumented stuff from Discord)

**Comment by Dworv** [comment]
No, you don't understand. I'm moving the sanitization to `Serializable._c`. This means that stuff like this can work:
```
{
  "documented": 1
  "undocumented": 2 # this gets removed in sanitization
  "sub_object": {
    "documented: 3
    "undocumented": 4 # this errors because sub_object cant handle it and nothing removes it
  }
}
```
without WET code.

**Comment by i0bs** [comment]
The serialiser will just need to make sure we're properly introspecting the attributes of the dataclass. If you're still putting in `dataclass_v` for the validation aspect, then this seems fine

**Comment by Dworv** [comment]
I was planning on it, I only just realized how `__dict__` works when run on a class, now `dataclass_v` makes perfect sense.

Is this a a go-ahead?

**Comment by i0bs** [comment]
LGTM, I'll make a thorough review upon PR submission
